import type { Resume } from "@/types/resume";
import { generateId } from "./utils";

export function createDefaultResume(): Resume {
  return {
    id: generateId(),
    personalInfo: {
      firstName: "",
      lastName: "",
      title: "",
      email: "",
      phone: "",
      location: "",
      website: "",
      linkedin: "",
      github: "",
      summary: "",
    },
    sections: [
      {
        id: generateId(),
        type: "experience",
        title: "Work Experience",
        titleFa: "تجربه کاری",
        items: [],
        visible: true,
        order: 0,
      },
      {
        id: generateId(),
        type: "education",
        title: "Education",
        titleFa: "تحصیلات",
        items: [],
        visible: true,
        order: 1,
      },
      {
        id: generateId(),
        type: "skills",
        title: "Skills",
        titleFa: "مهارت‌ها",
        items: [],
        visible: true,
        order: 2,
      },
    ],
    settings: {
      templateId: "classic",
      primaryColor: "#2563eb",
      fontFamily: "Inter",
      fontSize: 10,
      lineHeight: 1.5,
      margins: { top: 20, bottom: 20, left: 20, right: 20 },
      paperSize: "a4",
      showDividers: true,
      showIcons: true,
      columnLayout: "single",
    },
    language: "en",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

export function createSampleResume(): Resume {
  return {
    id: generateId(),
    personalInfo: {
      firstName: "Alex",
      lastName: "Johnson",
      title: "Senior Software Engineer",
      email: "alex.johnson@email.com",
      phone: "+1 (555) 123-4567",
      location: "San Francisco, CA",
      website: "https://alexjohnson.dev",
      linkedin: "linkedin.com/in/alexjohnson",
      github: "github.com/alexjohnson",
      summary: "Results-driven Senior Software Engineer with 8+ years of experience building scalable web applications. Led migration of monolithic architecture to microservices, reducing deployment time by 60%. Passionate about clean code, performance optimization, and mentoring junior developers.",
    },
    sections: [
      {
        id: generateId(),
        type: "experience",
        title: "Work Experience",
        titleFa: "تجربه کاری",
        items: [
          {
            id: generateId(),
            title: "Senior Software Engineer",
            subtitle: "TechCorp Inc.",
            location: "San Francisco, CA",
            startDate: "2021-03",
            endDate: "",
            current: true,
            description: "",
            bullets: [
              "Architected and led development of a real-time analytics platform serving 2M+ daily active users, improving data processing speed by 340%",
              "Mentored a team of 5 junior developers, implementing code review practices that reduced production bugs by 45%",
              "Designed and implemented RESTful APIs handling 10,000+ requests per second with 99.9% uptime",
              "Spearheaded migration from monolithic architecture to microservices, reducing deployment time from 2 hours to 15 minutes",
            ],
            tags: ["React", "Node.js", "AWS", "Kubernetes"],
          },
          {
            id: generateId(),
            title: "Software Engineer",
            subtitle: "StartupXYZ",
            location: "Austin, TX",
            startDate: "2018-06",
            endDate: "2021-02",
            current: false,
            description: "",
            bullets: [
              "Built and maintained customer-facing React applications used by 500K+ monthly active users",
              "Optimized database queries reducing average response time from 800ms to 120ms",
              "Implemented automated testing pipeline increasing code coverage from 35% to 89%",
            ],
            tags: ["React", "TypeScript", "PostgreSQL", "Docker"],
          },
        ],
        visible: true,
        order: 0,
      },
      {
        id: generateId(),
        type: "education",
        title: "Education",
        titleFa: "تحصیلات",
        items: [
          {
            id: generateId(),
            title: "Bachelor of Science in Computer Science",
            subtitle: "University of Texas at Austin",
            location: "Austin, TX",
            startDate: "2014-08",
            endDate: "2018-05",
            current: false,
            description: "",
            bullets: ["GPA: 3.8/4.0", "Dean's List 2016-2018"],
            tags: [],
          },
        ],
        visible: true,
        order: 1,
      },
      {
        id: generateId(),
        type: "skills",
        title: "Skills",
        titleFa: "مهارت‌ها",
        items: [
          {
            id: generateId(),
            title: "Technical Skills",
            subtitle: "",
            location: "",
            startDate: "",
            endDate: "",
            current: false,
            description: "",
            bullets: [],
            tags: [
              "React",
              "TypeScript",
              "Node.js",
              "Python",
              "AWS",
              "Kubernetes",
              "Docker",
              "PostgreSQL",
              "MongoDB",
              "Redis",
              "GraphQL",
              "REST APIs",
              "CI/CD",
              "Git",
            ],
          },
        ],
        visible: true,
        order: 2,
      },
    ],
    settings: {
      templateId: "classic",
      primaryColor: "#2563eb",
      fontFamily: "Inter",
      fontSize: 10,
      lineHeight: 1.5,
      margins: { top: 20, bottom: 20, left: 20, right: 20 },
      paperSize: "a4",
      showDividers: true,
      showIcons: true,
      columnLayout: "single",
    },
    language: "en",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
